Replace gcs adapter

diff --git a/src/ghost/Dockerfile b/src/ghost/Dockerfile
--- a/src/ghost/Dockerfile
+++ b/src/ghost/Dockerfile
@@ -1,15 +1,13 @@
 FROM ghost:4.32.3-alpine
 
 # Install the GCS adapter.
-RUN mkdir -p /tmp/gcs ${GHOST_CONTENT}/adapters/storage/gcs && \
-    wget -O - "$(npm view @danmasta/ghost-gcs-adapter dist.tarball)" | tar xz -C /tmp/gcs && \
-    npm install --prefix /tmp/gcs/package --silent --only=production --no-optional --no-progress && \
-    mv /tmp/gcs/package/* ${GHOST_CONTENT}/adapters/storage/gcs
-
-# Remove the symlink and copy the config files.
-RUN rm -f /var/lib/ghost/config.development.json
-COPY config.development.json /var/lib/ghost/config.development.json
-COPY config.production.json /var/lib/ghost/config.production.json
+RUN mkdir -p content/adapters/storage/gcs && \
+    npm install ghost-v3-google-cloud-storage && \
+    mv node_modules/ghost-v3-google-cloud-storage/* content/adapters/storage/gcs/
 
 # Copy the themes
 COPY themes /var/lib/ghost/content/themes
+
+#HEALTHCHECK CMD curl --fail http://localhost:2368 || exit 1
+#
+#USER node
